label var iso_code3 "ISO code (3 digits)"
label var year_folder "year (folder containing the file)"
label var hh5d "Day of interview"
label var hh5m "Month of interview"
label var hh5y "Year of interview"
*label var hl3 "Relationship to the head"
label var sex "Sex"
label var hl5d "Day of birth"
label var hl5m "Month of birth"
label var hl5y "Year of birth"
label var age "Age"
label var ed3 "Ever attended school or pre-school"
label var ed4a "Highest level of education attended"
label var ed4b "Highest grade completed at that level"
label var ed5 "Attended school during current school year"
label var ed6a "Level of education attended current school year"
label var ed6b "Grade of education attended current school year"
label var code_ed4a "ed4a: Created code, highest level ever attended"
label var code_ed6a "ed6a: Created code, level currently attended"
label var eduyears_B "Years of education (type B)"
label var eduyears_C "Years of education (type C)"
label var urban "Urban/rural"
label var hh6 "Area (original variable)"
label var hh7 "Region (original variable)"
label var region "Region_alternative"
label var ethnicity "Ethnicity of household head"
label var religion "Religion of household head"
label var hhweight "Household sample weight"
label var wealth "Wealth index quintiles"
label var schage "Age at beginning of school year"

